# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqM2BhrXuJeT_xd1CCyWWRDJ5YETDnIE

Q1. What is the purpose of Python&#39;s OOP?

The purpose of Python's Object-Oriented Programming (OOP) is to provide a way to organize and structure code in a more intuitive and modular way, making it easier to write, understand, and maintain complex applications.

OOP in Python revolves around the concept of objects, which are instances of classes. Classes are essentially blueprints or templates that define the attributes and behavior of objects of that class. By defining classes, you can create custom types with their own methods and attributes, which can then be used to create instances of those objects.

Q2. Where does an inheritance search look for an attribute?

In Python, when an attribute is accessed on an instance of a class, the interpreter first looks for the attribute within the instance itself. If the attribute is not found within the instance, the interpreter looks for it within the class of the instance.
If the attribute is not found within the class, the interpreter then looks for it in the parent classes of the class in a process known as inheritance search. The search proceeds from the immediate parent class up through the hierarchy of parent classes, and if the attribute is not found in any of the parent classes, it raises an AttributeError.

Q3. How do you distinguish between a class object and an instance object?

In Python, a class object is an object that represents a class, while an instance object is an object that is created from a class. Here are some key differences between class objects and instance objects:

1. Class objects are created when the interpreter reads the class definition, while instance objects are created at runtime when you call the class constructor.
2. Class objects have attributes that belong to the class itself, such as class methods and class variables, while instance objects have attributes that belong to each individual instance of the class
3. Class objects are usually used to define behavior and properties that are common to all instances of the class, while instance objects represent specific instances of the class with their own unique characteristics.
4. You can access class attributes and methods using the class object itself, while you can access instance attributes and methods using the instance object.

Q4. What makes the first argument in a class’s method function special?

When you call a method on an instance of a class, Python automatically passes the instance as the first argument to the method. This allows you to access the instance's attributes and methods from within the method.

The self argument is a reference to the instance itself, so any changes made to self within the method will affect the instance.

The self argument is conventionally named self, but you can use any valid variable name as long as it is the first argument in the method definition.

When you define a method in a class, you must include the self argument as the first parameter, even though you don't need to explicitly pass it when you call the method.

Q5. What is the purpose of the __init__ method?

The __init__ method is called automatically when an instance of the class is created, and it is used to set up the initial state of the instance.

The __init__ method takes the instance object self as its first argument, followed by any other arguments that are needed to initialize the instance's attributes.

The self parameter is a reference to the instance of the class that is being created, and it is used to set the instance's attributes.

You can define any number of parameters in the __init__ method, depending on how many attributes you need to initialize.

Q6. What is the process for creating a class instance?

Define the class: First, you need to define the class by using the class keyword followed by the class name. Inside the class, you define the attributes and methods that the instances of the class will have.

Create the instance: To create an instance of the class, you call the class as if it were a function, passing any required arguments to the __init__ method. This will create a new instance of the class and return it.

Assign the instance to a variable: Finally, you need to assign the new instance to a variable so that you can refer to it later. This variable is now an object of the class and can be used to access its attributes and methods.
"""

class Rectangle:
    def __init__(self,length, width):
      self.length= length
      self.width= width

    def area(self):
      return self.length * self.width

rect= Rectangle(5,4)
print(rect.length)
print(rect.width)

print(rect.width)
print(rect.area())

"""Q7. What is the process for creating a class?

Use the class keyword: To define a new class, you start with the class keyword followed by the name of the class.

Define the attributes: Inside the class, you define the attributes that each instance of the class will have. You can define them as instance variables (i.e., attributes that are unique to each instance) or class variables (i.e., attributes that are shared by all instances of the class).

Define the methods: You can also define methods inside the class, which are functions that belong to the class and can be called on instances of the class. Methods can be used to perform operations on the attributes of the class or to provide some functionality to the user.
"""

class Triangle:
    def __init__(self,base,height):
      self.base=base
      self.height=height
    def area_T(self):
      return self.base*self.height* 0.5

tri=Triangle(4,5)
print(tri.base)
print(tri.height)

print(tri.area_T())

"""Q8. How would you define the superclasses of a class?

In Python, you can define a class hierarchy using inheritance. A class that inherits from another class is called a subclass, and the class it inherits from is called a superclass or parent class. To define the superclass of a class in Python, you simply list the superclass name in the parentheses after the subclass name when defining the subclass.
"""

class Animal:
    def __init__(self,species):
      self.species=species

    def make_a_sound(self):
      print("the Animal makes a sound")

class Dog(Animal):
    def __init__(self, name):
        super().__init__("Canine")
        self.name = name

def make_sound(self):
        print("Woof!")

class Cat(Animal):
    def __init__(self, name):
        super().__init__("Feline")
        self.name = name
    
    def make_sound(self):
        print("Meow!")

